[package]
name = "shelfsync"
version = "0.0.1"
description = "Secure cross-device library synchronization"
authors = ["jdluu"]
edition = "2021"
default-run = "shelfsync"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "shelfsync_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.50", features = ["full"] }
jni = "0.21.1"
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
tauri-plugin-store = "2"
uuid = { version = "1.22.0", features = ["v4", "fast-rng"] }
tokio-util = { version = "0.7.18", features = ["io"] }
log = "0.4.29"
env_logger = "0.11.9"
thiserror = "2.0.18"
zip = "8.2.0"
reqwest = { version = "0.13.2", default-features = false, features = ["stream", "json", "rustls"] }
rustls = { version = "0.23", features = ["ring"] }
tauri-plugin-notification = "2"
futures-util = "0.3"
rusqlite = { version = "0.38.0", features = ["bundled"] }
tauri-plugin-updater = "2.10.0"
deadpool-sqlite = "0.13.0"
tauri-plugin-process = "2"
quick-xml = { version = "0.41", features = ["serialize", "escape-html"] }
url = "2.5"
 base64 = "0.22"
 sha2 = "0.10"
 aes-gcm = "0.10.3"
 rand = "0.8"
 md-5 = "0.10"
 async-trait = "0.1"
 libc = "0.2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]

[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]

[dev-dependencies]
axum = "0.8.8"
axum-test = { version = "19.1.1", features = ["reqwest"] }
tempfile = "3.27.0"

[profile.release]
codegen-units = 1
lto = true
strip = true
panic = "abort"
opt-level = "s"

[[bin]]
name = "mock_gen"
path = "src/bin/mock_gen.rs"
