import type { Book, ConnectionInfo, Host } from "@/types/core";

export const MOCK_HOST: Host = {
  ip: "127.0.0.1",
  port: 9999,
  hostname: "Mock Host Library",
};

export const MOCK_CONNECTION_INFO: ConnectionInfo = {
  ...MOCK_HOST,
  pin: "1234",
};

export const MOCK_BOOKS: Book[] = [
  {
    id: 1,
    title: "The Rust Programming Language",
    authors: "Steve Klabnik, Carol Nichols",
    path: "Rust/The Rust Programming Language.epub",
    formats: ["epub"],
    series: null,
    series_index: null,
    tags: ["Programming", "Rust", "Technology"],
    published_date: "2018-05-01T00:00:00Z",
  },
  {
    id: 2,
    title: "Dune",
    authors: "Frank Herbert",
    path: "Frank Herbert/Dune/Dune.epub",
    formats: ["epub"],
    series: "Dune",
    series_index: 1.0,
    tags: ["Science Fiction", "Classic"],
    published_date: "1965-08-01T00:00:00Z",
  },
  {
    id: 3,
    title: "Dune Messiah",
    authors: "Frank Herbert",
    path: "Frank Herbert/Dune/Dune Messiah.epub",
    formats: ["epub"],
    series: "Dune",
    series_index: 2.0,
    tags: ["Science Fiction", "Classic"],
    published_date: "1969-01-01T00:00:00Z",
  },
  {
    id: 4,
    title: "Children of Dune",
    authors: "Frank Herbert",
    path: "Frank Herbert/Dune/Children of Dune.epub",
    formats: ["epub"],
    series: "Dune",
    series_index: 3.0,
    tags: ["Science Fiction", "Classic", "Philosophy"],
    published_date: "1976-01-01T00:00:00Z",
  },
  {
    id: 5,
    title: "Clean Code",
    authors: "Robert C. Martin",
    path: "Agile/Clean Code.epub",
    formats: ["epub", "pdf"],
    series: "Agile Software Development",
    series_index: 1.0,
    tags: ["Programming", "Software Engineering"],
    published_date: "2008-08-01T00:00:00Z",
  },
  {
    id: 6,
    title: "System Design Interview",
    authors: "Alex Xu",
    path: "Tech/System Design Interview.epub",
    formats: ["epub", "mobi"],
    series: null,
    series_index: null,
    tags: ["Programming", "Architecture", "Interview"],
    published_date: "2020-06-12T00:00:00Z",
  },
  {
    id: 7,
    title: "The Three-Body Problem",
    authors: "Cixin Liu",
    path: "SciFi/The Three-Body Problem.epub",
    formats: ["epub"],
    series: "Remembrance of Earth's Past",
    series_index: 1.0,
    tags: ["Science Fiction", "Chinese Literature"],
    published_date: "2008-01-01T00:00:00Z",
  },
  {
    id: 8,
    title: "The Dark Forest",
    authors: "Cixin Liu",
    path: "SciFi/The Dark Forest.epub",
    formats: ["epub"],
    series: "Remembrance of Earth's Past",
    series_index: 2.0,
    tags: ["Science Fiction", "Chinese Literature"],
    published_date: "2015-08-11T00:00:00Z",
  },
  {
    id: 9,
    title: "Death's End",
    authors: "Cixin Liu",
    path: "SciFi/Death's End.epub",
    formats: ["epub"],
    series: "Remembrance of Earth's Past",
    series_index: 3.0,
    tags: ["Science Fiction", "Chinese Literature"],
    published_date: "2016-09-20T00:00:00Z",
  },
  {
    id: 10,
    title: "Project Hail Mary",
    authors: "Andy Weir",
    path: "Andy Weir/Project Hail Mary.epub",
    formats: ["epub"],
    series: null,
    series_index: null,
    tags: ["Science Fiction", "Space"],
    published_date: "2021-05-04T00:00:00Z",
  },
];
